name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build distributions
        run: |
          python -m build --sdist --wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.6.3
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
